[2024-11-18T07:50:35.112+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-11-18T07:50:32.649436+00:00 [queued]>
[2024-11-18T07:50:35.117+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-11-18T07:50:32.649436+00:00 [queued]>
[2024-11-18T07:50:35.117+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-18T07:50:35.124+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-11-18 07:50:32.649436+00:00
[2024-11-18T07:50:35.126+0000] {standard_task_runner.py:57} INFO - Started process 311 to run task
[2024-11-18T07:50:35.128+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2024-11-18T07:50:32.649436+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia.py', '--cfg-path', '/tmp/tmp18th1gri']
[2024-11-18T07:50:35.129+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask extract_data_from_wikipedia
[2024-11-18T07:50:35.162+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-11-18T07:50:32.649436+00:00 [running]> on host scheduler
[2024-11-18T07:50:35.216+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Clarkson' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T07:50:32.649436+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T07:50:32.649436+00:00'
[2024-11-18T07:50:35.217+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: get_wikipedia_data() missing 1 required positional argument: 'html'
[2024-11-18T07:50:35.223+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, execution_date=20241118T075032, start_date=20241118T075035, end_date=20241118T075035
[2024-11-18T07:50:35.228+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task extract_data_from_wikipedia (get_wikipedia_data() missing 1 required positional argument: 'html'; 311)
[2024-11-18T07:50:35.269+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-18T07:50:35.281+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
