[2024-11-18T08:16:49.800+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transfrom_wikipedia_data manual__2024-11-18T08:16:44.986625+00:00 [queued]>
[2024-11-18T08:16:49.804+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transfrom_wikipedia_data manual__2024-11-18T08:16:44.986625+00:00 [queued]>
[2024-11-18T08:16:49.804+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-18T08:16:49.811+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transfrom_wikipedia_data> on 2024-11-18 08:16:44.986625+00:00
[2024-11-18T08:16:49.813+0000] {standard_task_runner.py:57} INFO - Started process 895 to run task
[2024-11-18T08:16:49.815+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transfrom_wikipedia_data', 'manual__2024-11-18T08:16:44.986625+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia.py', '--cfg-path', '/tmp/tmpkt0nrlxo']
[2024-11-18T08:16:49.817+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask transfrom_wikipedia_data
[2024-11-18T08:16:49.845+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_flow.transfrom_wikipedia_data manual__2024-11-18T08:16:44.986625+00:00 [running]> on host scheduler
[2024-11-18T08:16:49.958+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Clarkson' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transfrom_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T08:16:44.986625+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T08:16:44.986625+00:00'
[2024-11-18T08:16:49.966+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 77, in transform_wikipedia_data
    data = json.load(data)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
[2024-11-18T08:16:49.971+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=transfrom_wikipedia_data, execution_date=20241118T081644, start_date=20241118T081649, end_date=20241118T081649
[2024-11-18T08:16:49.977+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task transfrom_wikipedia_data ('str' object has no attribute 'read'; 895)
[2024-11-18T08:16:50.004+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-18T08:16:50.015+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
